image: Visual Studio 2017

build_script:
  - cmd: msbuild netstandardbuildtest\netstandardbuildtest.csproj /t:restore /p:Configuration=Release
  - cmd: msbuild netstandardbuildtest\netstandardbuildtest.csproj /t:pack /p:Configuration=Release

artifacts:
  - path: '*.nupkg'
  